### PR TITLE
161 acknowledge contributors

### PR DESCRIPTION
**Pull request by annaasklof**
At this point we only have internal contributors and therefore don't list any contributors for individual pages. Listing of external contributors and contributors per page will be added when it is needed.

### CODE REVIEW

**Comment by elinkronander** [comment]
@annaasklof you have no ORCID listed for yourself, is that on purpose? 
On mobile view, this makes "your" box smaller than the others, can that be solved by adding a blank space for ORCID maybe? I guess this might happen in the future as well so it would be nice to already have it covered.

**Comment by annaasklof** [comment]
Good catch! I edited so that boxes without orcid should be the same size as boxes with ordid on mobile view as well.

**Comment by LianeHughes** [comment]
Are you adding the contributors manually Anna, or is the information 'read in' from elsewhere/automated in some way?

**Comment by annaasklof** [comment]
All contributors are added manually in the file https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/161-acknowledge-contributors/data/CONTRIBUTORS.yaml. From there fetched to be displayed where they fit (editorial, advisory, external on contributors page and later, when we have external contributors, listed per page).

**Comment by elinkronander** [comment]
> Good catch! I edited so that boxes without orcid should be the same size as boxes with ordid on mobile view as well.

I still get different sized boxes, probably due to name and organisation ending up on 1 or more rows depending on length. Is it possible to hardcode a minimal size to these repeating elements? 
(this is a pet-peeve for me so we might just leave it as is since it looks good on the screen) any thoughts @LianeHughes @YvonneKallberg

**Comment by YvonneKallberg** [comment]
I don't know how to see what a branch will look like on the mobile so I can only have an opinion in general:
- Yes, it would be nice for the eyes if the boxes are of the same size regardless of amount of text (might require a max limit on how long an organization name can be)
- I doubt that mobile view will be used that much, it's not really the type of site that you go and check while on the bus, especially not the contributors page.

Hence, if an easy fix is available then go ahead, otherwise leave it as is. :-)

**Comment by annaasklof** [comment]
> I don't know how to see what a branch will look like on the mobile so I can only have an opinion in general:
> 
> * Yes, it would be nice for the eyes if the boxes are of the same size regardless of amount of text (might require a max limit on how long an organization name can be)
> * I doubt that mobile view will be used that much, it's not really the type of site that you go and check while on the bus, especially not the contributors page.
> 
> Hence, if an easy fix is available then go ahead, otherwise leave it as is. :-)

Updated now, let me know what you think :)

**Pull request merged**
