### PR TITLE
add resources to each phase page based on their value in resources.json

### PR DESCRIPTION
**Pull request by annaasklof**
Here the resources listed on each of the pages in the data life cycle phases based on the phase they are listed as in resources.json. That way the resource list will update automatically every time a change is made in the resources.json file. However, due to the great amount of resources, only resources that apply to one specific phase are listed on the page of that phase.  This can of course be changed if we wish. 

For reference:

Phase - # resources with only that phase - # resources with that phase
Plan - 6 - 20
Collect - 4 - 15
Process - 2 - 9
Analyse - 6 - 14
Preserve - 1 - 6
Share - 6 -18
Reuse - 6 - 9

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
* I thought that the title wasn't enough to display on the individual pages, so I added the type. What do you think?
* Also, I missed one of the resources since it was connected to 2 phases (OpenRefine module), so I increased the limit to two. I do agree that listing more than 10 resources on a page makes it difficult to overview, so a limit is indeed needed. Question is if we perhaps should go through the resources and see if all phases should be there? There might be other resources that we really would want to be displayed in a phase or two, but since there are more than that at the moment, they are not displayed.
* An idea: Would it be possible to have a link to the resource table, with filters selected already, e.g. on Plan page there would be a link 'Plan resources' that would lead to /resources with plan filter prefilled? Or, seeing that the filter is not visible in the URL, is this not possible with hugo?

**Comment by annaasklof** [comment]
- I think it was a good idea to add the resource type. Do you want it to be in square brackets like it is now? (I think it looks good, just want to make sure)
- I agree that we can change the limit to 2, or even higher. And as you suggest I think it would be beneficial to go through all the resources and be more restrictive in their assigned phases if possible. 
- Would you like to have this as an addition to the list of resources on each phase page?

**Comment by YvonneKallberg** [comment]
* I do like that there is something that separates the type from normal/other text, but it doesn't have to be [ ]
*  I can do a run-through of the resources and see if some of them should be more restrictive. 
* So you think such a pre-filtered link is possible? Yes, I think I would like it as an addition, and if possible make the link appear as last bullet, always. This way we highlight central resources, and make the reader aware that other resources (might) exist. It could even be named 'Additional resources' / 'See all <phase> resources'

**Comment by annaasklof** [comment]
@YvonneKallberg 

Now resources are divided by type, all resources tagged with a specific phase in included (except resources tagged with all seven phases).

**Review by YvonneKallberg — COMMENTED** [review]
How are resources sorted within the type? In the guidance section of share page, the RDMkit links  aren't displayed one after another, so I guess not alphabetically? I'm not saying that they have to be sorted alphabetically, some resources might be of higher value, but I would like to have the same type of resource grouped (e.g. all RDMkit pages). Otherwise it looks good.

**Comment by annaasklof** [comment]
@YvonneKallberg They are sorted based on the order they are listed in resources.json.

**Pull request merged**
