### PR TITLE
Add ascp info on data-transfer

### PR DESCRIPTION
**Pull request by YvonneKallberg**

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
Please check not only typos and appearance but also if the instructions make sense or if more or less details are needed

**Comment by YvonneKallberg** [comment]
I see what you mean, since aspera could be installed by anyone (but with some difficulty to find the client to download since IBM really wants you to pay for their products), but I put it as subheading since it is instructions on how to use it on Uppmax (other HPCs don't have it).

**Comment by annaasklof** [comment]
I understand, maybe then we could call it 'Using Aspera on Uppmax"?

**Comment by YvonneKallberg** [comment]
Done

**Pull request merged**
