### PR TITLE
188 sticky breadcrumbs

### PR DESCRIPTION
**Pull request by annaasklof**
The breadcrumbs have been made sticky and the toc is still sticky.

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
Seems to work, well done! Did you try having the white part sticky, or is this too big portion of what is seen? 

Also, we talked about having also the title in ToC, so that it is easy to reach the top again. Though, I played around a bit and realised that there will be an indentation which doesn't look very nice. Any ideas on how to reach the goal but still look good?

**Comment by annaasklof** [comment]
Yes I did also tried having the navbar sticky. I think that also works well. We can compare the two options and see which one we prefer.

**Review by YvonneKallberg — APPROVED** [review]
This works well, approved

**Review by YvonneKallberg — CHANGES_REQUESTED** [review]
Spoke too hasty, using the TOC scrolls down too far, the title is not visible

**Review by YvonneKallberg — APPROVED** [review]
Works as expected now

**Pull request merged**
