### PR TITLE
244 add elixir rdm video

### PR DESCRIPTION
**Pull request by YvonneKallberg**

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
I changed the name of 'About RDM' to 'What is RDM?', but haven't checked content since I wrote the page before summer. A question, I've added the Resource link (RDMkit on Your role) to the training-filter branch, but should we also have the ELIXIR video as a resource-card? And, thinking of it, something that we use in our course is the [PANDA-movie](https://www.youtube.com/watch?v=66oNv_DJuPc), is this something we should have on the what-is page and / or added as resource-card?

**Comment by YvonneKallberg** [comment]
Saw this in our [advisory meeting notes](https://scilifelab.atlassian.net/wiki/spaces/SDMCS/pages/2523561997/RDM+Guidelines+2023-08-29): "Additional comment from Niclas: keep the video on the topic page since it is not “owned” by us. Move the text from the banner down with a heading like What is RDM and link directly to the topic page from there. Also clearly state that the video is from ELIXIR." I can add statement regarding the video, but should we also do the changes to the banner is this PR?

**Comment by elinkronander** [comment]
I think we should make another issue for the banner change and go ahead with adding this topic.

**Comment by elinkronander** [comment]
let's discuss this next editorial meeting before doing a merge

**Comment by annaasklof** [comment]
When clicking on the video link https://www.youtube.com/watch?v=S7HfUe1hWc it says "This video isn't available anymore".

**Comment by YvonneKallberg** [comment]
Fixed the youtube link

**Pull request merged**
