### PR TITLE
84 shift in visual identity

### PR DESCRIPTION
**Pull request by LianeHughes**
We might need to delete older iterations of the banner here, but I have put them all in for now!

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
Are we also changing from grape to teal on the data-life-cycle and topics pages? If so, shouldn't this also be part of this PR?

**Comment by annaasklof** [comment]
I changed the color of the topic links now, was that what you meant @YvonneKallberg?

**Comment by YvonneKallberg** [comment]
Ah, sorry, I was unclear. I meant the 'background banner picture' (not sure what to call it), the one with bubbles, that are on all pages except the main.

**Comment by LianeHughes** [comment]
Hey, the bubble image is in teal on mine, so it might be a cache issue. See if it changes for you Yvonne when you empty your cache?

**Comment by YvonneKallberg** [comment]
Indeed, cache issue, should have thought about that...

**Comment by LianeHughes** [comment]
No worries! Feel free to merge this if you're happy with the latest version

**Pull request merged**
