### PR TITLE
170 transfer information from dsw appendix to rdm guidelines

### PR DESCRIPTION
**Pull request by YvonneKallberg**
Solving also issue #189

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
A bit much in this PR, but the sharing page changes should be without major objections (at least I think that the texts explaining the picture is an improvement. As for the metadata, well, this is something we need to discuss (again). 

- I have a need to link directly to information regarding file formats (in knowledge models in DSW) and would prefer to have that info here and not as part of DSW. 
- The references to repositories, in the original table, is not necessary for me so I removed them and restructured the table. This makes the table suitable to have in a metadata page (and not a sharing page)
- Question is if we need to rethink all the buttons, perhaps have more tables where we separate the quite dense information and have e.g. one table with metadata standards?

**Comment by annaasklof** [comment]
I agree, the edits on share page are good! 

Regarding the buttons, do you mean the ones of type class="collapse"?

**Comment by YvonneKallberg** [comment]
Yes, the collapse buttons on the metadata page. There are a lot of information presented in a quite ugly way, where preferred metadata standards and file formats are listed.

image

**Comment by YvonneKallberg** [comment]
We need to discuss if and how we want to use expandable buttons. I have now made two versions:

1. In metadata page, all expandable buttons are gone, replaced with headings and bold text
2. In share page, the expandable buttons is moved down one level so instead of on eg Genomics data level it is now on repository level i.e. all repositories is expandable buttons

I do think it is nice to hide details about eg ENA, but do we want to do this also on metadata page so that eg 'Gene expression - Transcriptomics' would be a button under heading 'Genomics data'?

**Comment by elinkronander** [comment]
@YvonneKallberg I also think it is nice to hide away some details by using the buttons and in addition, the buttons also serve the purpose of highlighting certain things. 
I think this could be done on the metadata page as well.

**Comment by YvonneKallberg** [comment]
Jag fattar inte hur jag ska kunna få in knappar/expandable cards i table of contents... Har försökt googla men det enda jag får upp är hur markdown headers kan dyka upp i TOC per automagi. Våra knappar är ju skriva i html, inte markdown, så det hjälper inte mig. Någon som har förslag på lösning?

**Pull request merged**
