### PR TITLE
Replaced organisation names with logos

### PR DESCRIPTION
**Pull request by annaasklof**
This includes: 
verify link to Data Centre 
set logos for the organisations in the about page in place of the headers

The task - make sure data life cycle is two words not one (lifecycle)- is solved by PR: Changed 'data life cyce' to 'research data life cycle' #66

The task - possibly add link to data platform as well- is already solved. 

Together this solves issue  #41.

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
I would like a bit more space between logo:s and the text above (belonging to another logo). Also, the NBIS logo should align to the left. Layout wise, I don't like that the logos are larger than the heading (Organisations behind...) (should it be Organizations, by the way?)

This is not a 'must' in order to approve the PR, and I'm not sure it is visually doable (i.e. would look good layout wise) but could we try a 2 columns wide 'table' with the logos in the first column and the about text in the second? There's a lot of text for SLL which might make it look weird, so perhaps not doable...

**Comment by LianeHughes** [comment]
Just to say let me know if you need a hand with any potential changes and that it should be 'organisations' for British English, so it's fine 0:) (as a rule, always 's' not 'z' for British)

**Comment by YvonneKallberg** [comment]
Thanks Liane, I'm always confused about what is British and what is American... Sometimes I wonder if my way of mixing the two sounds to you the same way as mixing Norwegian and Swedish would sound for me :-D

**Comment by LianeHughes** [comment]
No problem at all. It probably does sound similar for Norwegian/Swedish for you haha!

**Comment by annaasklof** [comment]
Thanks for the input! I have now changed the logos to be smaller than the heading (Organisations behind...) and added more spring between the text and the logos of the next organisation. 

I also did as suggested and put the logos to the left 'column'and the text to the right 'column'. I think it was a good idea @Yvonne! 

Regarding the NBIS logo, it has a white part to the left on it (bigger than what the SLL logos have) and I agree it was a bit disturbing in the previous layout. However, you don't notice it as much in this layout. I'm also unsure if we are allowed to edit the actual NBIS logo to remove that white part of it?

**Comment by YvonneKallberg** [comment]
Unless I have a very wide page, the SLL logos overlap with the about text
image

**Comment by annaasklof** [comment]
Ah thanks for noticing that. I'll have a look!

**Comment by YvonneKallberg** [comment]
Looks good.

**Pull request merged**
