### PR TITLE
Added autumn dates for event series Meet a DS

### PR DESCRIPTION
**Pull request by annaasklof**
Autumn 2023: 19 Sept, 24 Oct, 21 Nov, 12 Dec.

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
Will the description be updated closer to the events? I'm thinking of:

1. Will the title of the talk be added
2. The first sentence looks wrong ('Join X and Y **get** data management support') can be changed to 'Join X & Y **for** data..' or 'Join X & Y data management support', or something else (though I would prefer not to have 2 'and' as in 'Join X and Y **and get** data...')

**Comment by annaasklof** [comment]
As standard the title and description have been the same for all previous events. So anyone interested in the event will need to go to the actual event page to get more information. I suggest we keep it like that for maintenance purposes. 

However, I like your suggestion number 2 regarding 'and' and '&'.

**Comment by YvonneKallberg** [comment]
You mean to change the desc to 'Join SciLifeLab Data Centre **&** NBIS **and** get data management support.'? It was not my intention, I used '&' for shortening my typing, but I'm fine with that version. :-) Will you change or should I? I think we can merge after that, either way.

**Comment by annaasklof** [comment]
Ah I see, your suggestion with for is also good! You go ahead and change to whichever you prefer.

**Pull request merged**
