### PR TITLE
215 scilifelab data management support info

### PR DESCRIPTION
**Pull request by annaasklof**
- New page 'RDM support' added with the same information as the flyer prepared for SciLifeLab site visits
- New page also includes a a link to the digital version of the flyer 
- A copy of the current contact form is included on the new page 
- This new page is linked from the Get Support box on home page
- Link to this new page in top navbar

### CODE REVIEW

**Comment by YvonneKallberg** [comment]
- Need to add space in header btw RDM support, About and Contact. Compare with the row under with Home, Research data life cycle and Topics, where it is much better separation.
- There must be a better version of the flyer, the wheel is just weird with a white line around it, and the one on front page is badly aligned (bottom overlaps with the image below). Also, the text is a bit so-so
- 'Contact our team via email', email should be linked

**Comment by YvonneKallberg** [comment]
Remember to change 'Wish to' to 'Want to'

**Comment by YvonneKallberg** [comment]
I'm happy with the page now, but perhaps @elinkronander should have a look?

**Comment by elinkronander** [comment]
Great job! I will merge this now (for next time, feel free to merge without my review)

**Pull request merged**
